### ISSUE TITLE
During connection errors it takes a while to react on exit signal

### ISSUE THREAD

**Issue by sshumakov** [alvalor/alvalor-go#108]
I tried to run node and it gave me error connection:

`{"timestamp":"2018-02-25T15:06:10Z","level":"error","package":"network","component":"receiver","address":"127.0.0.1:1201","error":"could not decode proto message: read tcp 127.0.0.1:21519->127.0.0.1:1201: wsarecv: An existing connection was forcibly closed by the remote host.","message":"could not read message"}`

The thing is that this error connection was posted ~50 times per ~20 seconds and I couldn't really exit from app immediately after sending stop signal. It would be nice to respect stop signal and perhaps add some backoff mechanism in case we see connection error like this multiple times.

**Comment by sshumakov** [comment]
If you look at log message more closely, you will see that for some reason it mentions "address":"127.0.0.1:1201", I didn't use port 1201 explicitly anywhere.

**Comment by awishformore** [comment]
Basically, this is because the Go standard library doesn't allow proper detection of closed network connections when reading/writing, so we use a workaround that detects it by string-matching the error message. It seems the message is simply different on Windows.

See https://github.com/golang/go/issues/4373 for the full discussion.
