### ISSUE TITLE
Network score mechanism and active field filtering

### ISSUE THREAD

**Issue by sshumakov** [alvalor/alvalor-go#35]
It seems that network score mechanism has a bug regarding how score is calculated. For example, if node has 1 failure and 1 success, it would still have score of one due to this line of code:

`math.Max(score/100, 1)`

This means that it doesn't matter how many failures/drops it has, it would still go up to 1.

Another thing I noticed is active field filtering:

```
if !active && e.active {
     continue
}
entries = append(entries, e)
```
For the case when passed argument active == true and e.active == false, it would still add it to the result slice.

**Comment by awishformore** [comment]
The behaviour of the active filtering is correct.

It is there to make the distinction between:

1) sharing addresses with other peers; here we want a sample of all addresses, both active and not active ones, because our own connection state is irrelevant to the other peers
2) getting a sample or one address that we are not yet connected to; in this case, we only want to filter out the active addresses

The active flag should thus be understood as "include active peers" and works as expected.
